from tkinter import *

window = Tk()
window.geometry("1014x600")
f1 = LabelFrame(window)
f1.place(x=0,y=0)
l_1 = Label(f1,text='Account: {}',font=('Helvetica',12),width=113,anchor=W)
l_1.pack()
f2 = LabelFrame(window)
f2.place(x=0,y=27)
b_21 = Button(f2,text="Fund Transfer",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue')
b_22 = Button(f2,text="Withdraw/Deposit",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue')
b_23 = Button(f2,text="Account Details",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue')
b_24 = Button(f2,text="Logout",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue')
b_21.grid(row=0,column=0)
b_22.grid(row=0,column=1)
b_23.grid(row=0,column=2)
b_24.grid(row=0,column=3)

window.resizable(False,False)
window.mainloop()
