from tkinter import *
from datetime import date
def services():

    def cancel():
            window.destroy()
            services()


    def fund_transfer():
        b_21.config(state=DISABLED)
        b_22.config(state=DISABLED)
        b_23.config(state=DISABLED)
        b_24.config(state=DISABLED)
        today = date.today()
        d = today.strftime("%b-%d-%Y")
        l_frmacc = Label(l_3,text="From Account: ",font=("Helvetica",20),bg="light grey")
        l_frmacc.place(x=20,y=30)
        l_toacc = Label(l_3,text="To Account: ",font=("Helvetica",20),bg="light grey")
        l_toacc.place(x=20,y=130)
        l_amt = Label(l_3,text="Amount: ",font=("Helvetica",20),bg="light grey")
        l_amt.place(x=20,y=230)
        l_date = Label(l_3,text="Date: ",font=("Helvetica",20),bg="light grey")
        l_date.place(x=20,y=330)

        l_frmacc2 = Label(l_3,text="xxxxxxxx@gmail.com",font=("Helvetica",20),bg="light grey")
        l_frmacc2.place(x=250,y=30)
        e_toacc = Entry(l_3,font=("Helvetica",20),width=25)
        e_toacc.place(x=250,y=130)
        e_amt = Entry(l_3,font=("Helvetica",20))
        e_amt.place(x=250,y=230)
        l_date2 = Label(l_3,text=d,font=("Helvetica",20),bg="light grey")
        l_date2.place(x=250,y=330)
        bs_cancel = Button(l_3,text="Cancel Transfer",font=("Helvetica",18),command=cancel)
        bs_cancel.place(x=640,y=450)
        bs_proceed = Button(l_3,text="Proceed",font=("Helvetica",18),bg="red",fg="white")
        bs_proceed.place(x=850,y=450)

    def account_details():
        b_21.config(state=DISABLED)
        b_22.config(state=DISABLED)
        b_23.config(state=DISABLED)
        b_24.config(state=DISABLED)
        ld_name = Label(l_3,text="Name: ",font=("Helvetica",20),bg="light grey")
        ld_name.place(x=20,y=30)
        ld_id = Label(l_3,text="Email ID: ",font=("Helvetica",20),bg="light grey")
        ld_id.place(x=20,y=120)
        ld_mob = Label(l_3,text="Mobile Number: ",font=("Helvetica",20),bg="light grey")
        ld_mob.place(x=20,y=210)
        ld_type = Label(l_3,text="Type of Account: ",font=("Helvetica",20),bg="light grey")
        ld_type.place(x=20,y=300)
        ld_balance = Label(l_3,text="Account Balance: ",font=("Helvetica",20),bg="light grey")
        ld_balance.place(x=20,y=390)

        ld_name2 = Label(l_3,text="xxxxxxxxxxx",font=("Helvetica",20),bg="light grey")
        ld_name2.place(x=310,y=30)
        ld_id2 = Label(l_3,text="xxxxxxxxxxx@gmail.com",font=("Helvetica",20),bg="light grey")
        ld_id2.place(x=310,y=120)
        ld_mob2 = Label(l_3,text="0000000000",font=("Helvetica",20),bg="light grey")
        ld_mob2.place(x=310,y=210)
        ld_type2 = Label(l_3,text="Savings Account",font=("Helvetica",20),bg="light grey")
        ld_type2.place(x=310,y=300)
        ld_balance2 = Label(l_3,text="000000000",font=("Helvetica",20),bg="light grey")
        ld_balance2.place(x=310,y=390)
        bd_goback  = Button(l_3,text="Go Back",font=("Helvetica",18),bg="red",fg="white",command=cancel)
        bd_goback.place(x=850,y=450)


    window = Tk()
    window.title("Services")
    window.geometry("1014x600")
    f1 = LabelFrame(window)
    f1.place(x=0,y=0)
    l_1 = Label(f1,text='Account: {}',font=('Helvetica',12),width=112,anchor=W)
    l_1.pack()
    f2 = LabelFrame(window)
    f2.place(x=0,y=27)
    b_21 = Button(f2,text="Fund Transfer",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue',command=fund_transfer)
    b_22 = Button(f2,text="Recent Activity",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue')
    b_23 = Button(f2,text="Account Details",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue',command=account_details)
    b_24 = Button(f2,text="Logout",font=("Helvetica",13),width=27,pady=8,bg="light blue",fg='blue')
    b_21.grid(row=0,column=0)
    b_22.grid(row=0,column=1)
    b_23.grid(row=0,column=2)
    b_24.grid(row=0,column=3)
    f3 = LabelFrame(window)
    f3.place(x=0,y=75)
    l_3 = Label(f3,bg="light grey",padx=503,pady=251)
    l_3.pack()
    window.resizable(False,False)
    window.mainloop()

services()