from tkinter import *
wpass = Toplevel()
wpass.geometry("380x210")
wpass.title("Set Password")
l_password = Label(wpass,text="Password: ",font=("Helvetica",15))
l_password.place(x=5,y=10)
e_password = Entry(wpass,font=("Helvetica",15),borderwidth=5,width=25,show="*")
e_password.place(x=5,y=40)
l_cpassword = Label(wpass,text="Confirm Password: ",font=("Helvetica",15))
l_cpassword.place(x=5,y=90)
e_cpassword = Entry(wpass,font=("Helvetica",15),borderwidth=5,width=25,show="*")
e_cpassword.place(x=5,y=120)
b_create = Button(wpass,text="Create Account",font=("Helvetica",13),bg="blue",fg="white")
b_create.place(x=230,y=170)
b_cancel = Button(wpass,text="Cancel",font=("Helvetica",13))
b_cancel.place(x=150,y=170)
wpass.mainloop()